### ISSUE TITLE
NfQueue library missing

### ISSUE THREAD

**Issue by ppacher** [Safing/safing-installer#1]
Hi ;)

the installer currently misses to check if libnetfilter_queue.so.1 is actually present on the system. This causes safing-core to exit immediately while safing-ui and safing-notify still try to connect. Moreover, I didn't found any notice in the docs (though, they are great).

If I find some time I'll fix it and file a pull request. Should we create a separate issue on safing-core to add it to the docs (and maybe a check to the build file)?

Cheers,
Patrick

**Comment by dhaavi** [comment]
Hi Patrick,

thank you for pointing this out. I added a check for this and released v0.0.2.

`libnetfilter_queue` is actually mentioned as a dependency in the Safing Core readme, but it was a bit unclear, as it was only mentioned in the development section. I clarified this.

cheers,
Daniel
